cd /home/rasmiranjan/Desktop/
cd loyalty
rm loyalty-0.0.1-SNAPSHOT.war
cd ..
cd user-service/
rm user-service-0.0.1-SNAPSHOT.jar
cd ..
cd loyalty-entity-service/
rm loyalty-entity-service-0.0.1-SNAPSHOT.jar
cd ..
cd loyalty-management-service/
rm loyalty-management-service-0.0.1-SNAPSHOT.jar
cd ..
cd transaction-service
rm transaction-service-0.0.1-SNAPSHOT.jar
cd ..
cd behavioral-service/
rm loyalty-behavioural-service-0.0.1-SNAPSHOT.ja
cd ..
cd loyalty-custom-offer-service/
rm custom-offers-service-0.0.1-SNAPSHOT.jar
cd ..
cd loyalty-reports-service/
rm loyalty-reports-service-0.0.1-SNAPSHOT.jar
